name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      # Define service URLs
      MATH_SERVICE_URL: http://math-service:4001
      HISTORY_SERVICE_URL: http://history-service:4002
      GEOGRAPHY_SERVICE_URL: http://geography-service:4003

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full repo is cloned

      # 2. List repository files (debugging)
      - name: List repository files
        run: ls -R

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          cd frontend && npm install
          [[ -d services/api-gateway ]] && cd ../services/api-gateway && npm install || echo "api-gateway directory not found!"
          [[ -d services/math-service ]] && cd ../
